"""created image column in  buses

Revision ID: 16725967aa1c
Revises: 81e39a62edc1
Create Date: 2023-08-02 17:11:04.012736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16725967aa1c'
down_revision = '81e39a62edc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
