"""updates in models

Revision ID: 87054ccbd09e
Revises: f24d043feabf
Create Date: 2023-08-04 22:32:21.892771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87054ccbd09e'
down_revision = 'f24d043feabf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visits', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_column('visits')

    # ### end Alembic commands ###
