"""added password'


Revision ID: 897bd4216882
Revises: b0dfeb6bf884
Create Date: 2023-08-08 16:24:35.599372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897bd4216882'
down_revision = 'b0dfeb6bf884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=True))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
