"""uploads update

Revision ID: a336b3b4cc28
Revises: 7c79e17e2f42
Create Date: 2023-08-05 12:55:34.505771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a336b3b4cc28'
down_revision = '7c79e17e2f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('visits', sa.Integer(), nullable=True),
    sa.Column('bus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], name=op.f('fk_uploads_bus_id_buses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploads'))
    )
    op.drop_table('upload')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_upload')
    )
    op.drop_table('uploads')
    # ### end Alembic commands ###
