"""changes

Revision ID: bd6eb7eb94d3
Revises: 7c79e17e2f42
Create Date: 2023-08-04 14:08:37.151552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6eb7eb94d3'
down_revision = '7c79e17e2f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nationality', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('nationality')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
