"""change1

Revision ID: c136058b8116
Revises: bd6eb7eb94d3
Create Date: 2023-08-04 15:27:16.184346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c136058b8116'
down_revision = 'bd6eb7eb94d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phoneNumber', sa.Integer(), nullable=True))
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.INTEGER(), nullable=True))
        batch_op.drop_column('phoneNumber')

    # ### end Alembic commands ###
