"""updates in models

Revision ID: f24d043feabf
Revises: 9852efc6460f
Create Date: 2023-08-04 22:20:23.061931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f24d043feabf'
down_revision = '9852efc6460f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bus_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_uploads_bus_id_buses'), 'buses', ['bus_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_uploads_bus_id_buses'), type_='foreignkey')
        batch_op.drop_column('bus_id')

    # ### end Alembic commands ###
