"""corrected the models

Revision ID: f50dd0b100ad
Revises: 74ba8db37566
Create Date: 2023-08-08 10:05:27.330978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50dd0b100ad'
down_revision = '74ba8db37566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('visits', sa.Integer(), nullable=True),
    sa.Column('bus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], name=op.f('fk_uploads_bus_id_buses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploads'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nationality', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phoneNumber', sa.Integer(), nullable=True))
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.INTEGER(), nullable=True))
        batch_op.drop_column('phoneNumber')
        batch_op.drop_column('nationality')
        batch_op.drop_column('full_name')

    op.drop_table('uploads')
    # ### end Alembic commands ###
